org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# 本地代理设置（CI/CD 环境无需代理；若本地需要可取消注释，或更推荐配置在 ~/.gradle/gradle.properties）
# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=7890
# systemProp.http.nonProxyHosts=localhost|127.0.0.1
# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=7890
# systemProp.https.nonProxyHosts=localhost|127.0.0.1
